### ISSUE TITLE
Evaluation results disappear

### ISSUE THREAD

**Issue by aqzhang218** [Sauf4896/monodepth2-ddp#1]
Thank you very much for providing the code about DDP, it is a good job. But I was using Resnet50 for monocular + stereoscopic training and found that the training results disappeared. Could you please give me an answer? Have you ever run this code with Resnet50?
![image](https://github.com/user-attachments/assets/e7163740-3a7b-4098-8fcb-479a40690203)

**Comment by LiuJF1226** [comment]
Hi, this project was too long ago. I can't remember the details. How about ResNet18 + MS training? Or ResNet50 + M， ResNet50 + S settings？ Have you tried these?
